# Generated by Django 5.2.4 on 2025-12-28 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('FEMA', 'FEMA'), ('SEBI', 'SEBI'), ('Corporate Law', 'Corporate Law'), ('Fundraising', 'Fundraising'), ('Startups', 'Startups'), ('Compliance', 'Compliance')], max_length=50)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.IntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('industry', models.CharField(choices=[('Technology', 'Technology'), ('Manufacturing', 'Manufacturing'), ('Finance', 'Finance'), ('Startups', 'Startups'), ('Healthcare', 'Healthcare'), ('Retail', 'Retail'), ('Pharmaceuticals', 'Pharmaceuticals')], max_length=50)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='testimonial_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('services', models.CharField(blank=True, help_text='Comma-separated service tags', max_length=200)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
