# Generated by Django 5.2.4 on 2025-12-30 12:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.CharField(choices=[('30', '30 Minutes'), ('45', '45 Minutes'), ('60', '60 Minutes')], default='60', max_length=10)),
                ('max_bookings', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('duration', models.CharField(choices=[('30-min', '30 Minutes'), ('45-min', '45 Minutes'), ('60-min', '60 Minutes')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('mode', models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Call'), ('in_person', 'In-person')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('topic', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='consultation_docs/')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('pending_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('newsletter_consent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Consultation Booking',
                'verbose_name_plural': 'Consultation Bookings',
                'ordering': ['-appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('industry', models.CharField(choices=[('Technology', 'Technology'), ('Manufacturing', 'Manufacturing'), ('Finance', 'Finance'), ('Startups', 'Startups'), ('Healthcare', 'Healthcare'), ('Retail', 'Retail'), ('Pharmaceuticals', 'Pharmaceuticals')], max_length=50)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='testimonial_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='testimonials/videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Thumbnail image for video testimonial', null=True, upload_to='testimonial_videos/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('services', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('FEMA', 'FEMA'), ('SEBI', 'SEBI'), ('Corporate Law', 'Corporate Law'), ('Fundraising', 'Fundraising'), ('Startups', 'Startups'), ('Compliance', 'Compliance')], max_length=50)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.IntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (optional)', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description (optional)', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0, editable=False)),
                ('author', models.ForeignKey(blank=True, help_text='Admin who created this post', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('Technology', 'Technology'), ('Manufacturing', 'Manufacturing'), ('Finance', 'Finance'), ('Startups', 'Startups'), ('Healthcare', 'Healthcare'), ('Retail', 'Retail'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Other', 'Other')], max_length=50)),
                ('testimonial_text', models.TextField()),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('services_used', models.CharField(blank=True, help_text='Comma-separated list of services used', max_length=200)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='testimonial_submissions/profiles/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('approved_testimonial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='pankaj.testimonial')),
            ],
            options={
                'verbose_name': 'Testimonial Submission',
                'verbose_name_plural': 'Testimonial Submissions',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='BookedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pankaj.availableslot')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pankaj.consultationbooking')),
            ],
            options={
                'unique_together': {('slot', 'date')},
            },
        ),
    ]
