# Generated by Django 5.2.4 on 2025-12-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial_videos/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube / Vimeo embed or direct video URL', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
