# Generated by Django 5.2.4 on 2025-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0002_testimonial_video_thumbnail_testimonial_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='services',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image for video testimonial', null=True, upload_to='testimonial_videos/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube / Vimeo embed or MP4 URL', null=True),
        ),
    ]
