# Generated by Django 5.2.4 on 2026-01-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0002_blogsubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationbooking',
            name='mode',
            field=models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Call')], max_length=20),
        ),
    ]
