# Generated by Django 5.2.4 on 2026-01-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0003_alter_consultationbooking_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogSubscriber',
        ),
    ]
