# Generated by Django 5.2.4 on 2025-12-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0003_alter_testimonial_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video',
            field=models.FileField(default=1, upload_to='testimonials/videos/'),
            preserve_default=False,
        ),
    ]
