# Generated by Django 5.2.4 on 2026-01-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0004_delete_blogsubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonialsubmission',
            name='company_name',
        ),
        migrations.AddField(
            model_name='testimonialsubmission',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialsubmission',
            name='industry',
            field=models.CharField(blank=True, help_text='e.g. Technology, Finance, Healthcare', max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonialsubmission',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
