# Generated by Django 5.2.4 on 2025-12-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0004_testimonial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='testimonials/videos/'),
        ),
    ]
