# Generated by Django 5.2.4 on 2025-12-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0005_alter_testimonial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
