# Generated by Django 5.2.4 on 2026-01-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0005_remove_testimonialsubmission_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='testimonialsubmission',
            name='approved_testimonial',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='industry',
            field=models.CharField(blank=True, help_text='e.g. Technology, Finance, Healthcare', max_length=100),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='TestimonialSubmission',
        ),
    ]
