# Generated by Django 5.2.4 on 2025-12-28 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0006_alter_testimonial_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('Technology', 'Technology'), ('Manufacturing', 'Manufacturing'), ('Finance', 'Finance'), ('Startups', 'Startups'), ('Healthcare', 'Healthcare'), ('Retail', 'Retail'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Other', 'Other')], max_length=50)),
                ('testimonial_text', models.TextField()),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('services_used', models.CharField(blank=True, help_text='Comma-separated list of services used', max_length=200)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='testimonial_submissions/profiles/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('approved_testimonial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='pankaj.testimonial')),
            ],
            options={
                'verbose_name': 'Testimonial Submission',
                'verbose_name_plural': 'Testimonial Submissions',
                'ordering': ['-submitted_date'],
            },
        ),
    ]
