# Generated by Django 5.2.4 on 2025-12-29 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0007_testimonialsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_bookings', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('duration', models.CharField(choices=[('30-min', '30 Minutes'), ('45-min', '45 Minutes'), ('60-min', '60 Minutes')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('mode', models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Call'), ('in_person', 'In-person')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('topic', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='consultation_docs/')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('newsletter_consent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Consultation Booking',
                'verbose_name_plural': 'Consultation Bookings',
                'ordering': ['-appointment_date', 'appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='BookedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pankaj.availableslot')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pankaj.consultationbooking')),
            ],
            options={
                'unique_together': {('slot', 'date')},
            },
        ),
    ]
