# Generated by Django 5.2.4 on 2025-12-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0008_availableslot_consultationbooking_bookedslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslot',
            name='duration',
            field=models.CharField(choices=[('30', '30 Minutes'), ('45', '45 Minutes'), ('60', '60 Minutes')], default='60', max_length=10),
        ),
    ]
