# Generated by Django 5.2.4 on 2025-12-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0009_availableslot_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
