# Generated by Django 5.2.4 on 2025-12-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pankaj', '0010_consultationbooking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='pending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
